theme: jekyll-theme-cayman
title: "Improving Community Health with Renewable Energy Source"
description: Applied Panel Regression, Breusch-Pagan test, the Hausman test, and the Granger Causality test to examine the relationship between non-renewable energy consumption and asthma prevalence. 
